#Server Port
server:
  port: 8765

#Zuul routes active
zuul:
  routes:
    public-restservice:
      path: /public/**
      serviceId: public-restservice

#Eureka instance ID
eureka:
  instance:
    instanceId: ${spring.application.name}:${server.port}

#Ribbon Activation
ribbon:
  eureka:
    enabled: true






